services:
  web:
    build: .
    container_name: bank_app
    ports:
      - "5000:5000" 
    volumes:
      - .:/app  
      - ./data:/app/data
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
